obj-$(CONFIG_MTD_NAND_QEMU_3DNAND) += qemu_3dnand.o
qemu_3dnand-y := qemu_3dnand_module.o qemu_3dnand_init.o \
		 qemu_3dnand_flash.o ytmc_nand.o \
		 qemu_3dnand_controller.o qemu_3dnand_ecc.o \
		 qemu_3dnand_addr.o qemu_3dnand_hw.o
